[package]
name = "tests-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
tabled = "0.16"
insta = "1"
rustdx-complete = { path = "../" }
rustdx-cmd = { path = "../rustdx-cmd" }
chrono = { workspace = true }

